# Generated by Django 5.1.7 on 2025-03-09 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("order_number", models.CharField(max_length=6, unique=True)),
                ("customer_name", models.CharField(max_length=256)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(max_length=256)),
                (
                    "waypoint_type",
                    models.CharField(choices=[("pickup", "Pickup"), ("delivery", "Delivery")], max_length=8),
                ),
                ("sequence", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="waypoints", to="core.order"
                    ),
                ),
            ],
            options={
                "db_table": "waypoint",
            },
        ),
    ]
